# Generated by Django 4.1.4 on 2022-12-07 17:10

from django.db import migrations, models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='service image')),
                ('heading', models.CharField(max_length=100)),
                ('discription', tinymce.models.HTMLField()),
                ('image2', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testimagemodel/', verbose_name='service image2')),
                ('image3', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testimagemodel/', verbose_name='service image3')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
