# Generated by Django 4.1.4 on 2022-12-08 04:40

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimage', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/testmoedel/', verbose_name='gallery image')),
            ],
        ),
    ]
