# Generated by Django 4.1.4 on 2022-12-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_career'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='name',
            new_name='jobname',
        ),
    ]
