# Generated by Django 4.1.4 on 2022-12-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_name_career_jobname'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='contenttitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
