# Generated by Django 4.1.4 on 2022-12-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_services_contenttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('resume', models.FileField(upload_to='image/testmoedel/')),
                ('jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.career')),
            ],
        ),
    ]
