# Generated by Django 4.1.4 on 2022-12-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_careerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdata',
            name='jobs',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
