# Generated by Django 4.1.4 on 2022-12-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_careerdata_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='discription',
            field=models.TextField(),
        ),
    ]
